### **DATA NUMERIK**

In [41]:
x = 3+5j
print(type(x))

<class 'complex'>


In [47]:
import random as rd
print(rd.randrange(1,10))
a = ['aku', 'kamu', 'dia', 'kita' ]
print(rd.choices(a))
print(dir(rd))

9
['kamu']
['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', '_ONE', '_Sequence', '_Set', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_accumulate', '_acos', '_bisect', '_ceil', '_cos', '_e', '_exp', '_floor', '_index', '_inst', '_isfinite', '_log', '_os', '_pi', '_random', '_repeat', '_sha512', '_sin', '_sqrt', '_test', '_test_generator', '_urandom', '_warn', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randbytes', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [4]:
# excercise 1 
# buat program untuk konversi nilai mata kuliah 
a = float(input('Masukkan nilai'))
if a > 100 or a< 0:
    print('range angka harus diantara 0-100')
elif a >= 86:
    print('A')
elif a >= 78:
    print('B')
elif a >= 68:
    print('C')
elif a >= 55:
    print('D')
elif a < 55:
    print('E') 

range angka harus diantara 0-100


In [5]:
# membandingkan bilangan
a = float(input('masukkan bilangan pertama: '))
b = float(input('masukkan bilangan kedua: '))

if a == b:
    print('seri, sama')
elif a < b:
    print(a, 'lebih kecil daripada', b)
elif a>b:
    print(a,'lebih besar daripada', b)
else:
    print('Error')


2.0 lebih kecil daripada 5.0


In [10]:
#random dengan AI
import random
a = int(input('Masukkan angka 1-30: '))
ai = int(random.randrange(1,30))
print(ai)

if a == ai:
    print('seri')
elif a > ai:
    print('anda menang')
elif a<ai:
    print('anda kalah')

7
anda kalah


In [ ]:
#convert dollar ke euro
def euroconvert(rupiah:int):
    return rupiah/17000
euroconvert(15000)

def dollarconvert(rupiah:int):
    return rupiah/15000
dollarconvert(15000)

rupiah = int(input('Masukkan nilai rupiah'))
NilaiDollar =print('Nilai Dollar adalah =', dollarconvert(rupiah))
NilaiEuro = print('Nilai Euro adalah =', euroconvert(rupiah))

In [1]:
# seleksi ganjil genap
for i in range(1,10):
    if i%2 == 0:
        print(f'{i} = genap')
    else:
        print(f'{i} = ganjil')

1 = ganjil
2 = genap
3 = ganjil
4 = genap
5 = ganjil
6 = genap
7 = ganjil
8 = genap
9 = ganjil


In [16]:
#  buat kalkulator
def kal(num1,operator,num2):
    if operator == '+':
        return num1 + num2
    elif operator == '-':
        return num1 - num2
    elif operator == '/':
        return num1/num2
    elif operator == '*':
        return num1*num2

kal(2,'+',3)



5

In [16]:
# array seleksi ganjil genap dri inputan list sekaligus koma
import numpy as np
kata = input('masukkan list angka')
numbers = kata.split(',')
numbers = [int(x) for x in  numbers]
print(numbers)
arr= np.array(numbers)
print(arr)
ganjil = 0
genap = 0

for num in numbers:
     if num % 2 ==0:
         genap +=num
     else:
         ganjil +=num

dict = {
    'ganjil': [num for num in numbers if num%2==1],
    'genap': [num for num in numbers if num %2==0]
}
        
print(ganjil, genap)
print(dict)
print(sum(dict['ganjil']))
print(sum(dict['genap']))

[1, 2, 4, 5, 68, 9]
[ 1  2  4  5 68  9]
15 74
{'ganjil': [1, 5, 9], 'genap': [2, 4, 68]}
15
74


In [17]:
a ='hello'
print(a[1:2])

list = [1,2,3,4]
print(*list) #print list biar gaada titik
print(list)


e
1 2 3 4
[1, 2, 3, 4]


In [49]:
# jumlahkan ganjil genap sendiri

def jumlah_ganjil_genap(list):
    ganjil=0
    genap= 0
    for i in list:
        if i%2==0:
            genap+=1
        else:
            ganjil+=1
    return [ganjil, genap]

jumlah_ganjil_genap([1,3,4,6,4])

[2, 3]

In [13]:
# mengitung pangkat persatuan angka lalu dijumlah
def pangkat(num):
    return sum(x**2 for x in num)
pangkat([1,2,4,5])

46

In [20]:
# menghitung jumlah kuadrat angka dar list
a = input('masukkan angka')
num = a.split(',')
num = [int(x) for x in num]
print(sum(x**2 for x in num))
print(num)

14
[1, 2, 3]


In [20]:
listAngka= [1,7,8,9,9,11,13]
prima= [x for x in listAngka    if x>1 and all(x%i !=0 for i in range(2,x))]
print(prima)

[7, 11, 13]


In [ ]:
# membuat bintang segitiga
a= int(input())
for i in range(a, 0, -1):
    print((i)*'*')

In [ ]:
a=int(input('masukkan banyak baris: '))
for i in range(a):
    print((' ')* (a - i -1) + '*'*(2*i+1))

##### **soal praktikum numerik**

In [5]:
# no 1 menghitung faktor dari suatu bilangan, 4 -> 1, 2, 4
angka = int(input('masukkan angka yg akan difaktorkan: '))
faktor = []
for i in range(1, angka+1):
    if angka%i == 0:
        faktor.append(i)
print(faktor)

[1, 3]


In [8]:
# 2. mengitung luas dan keliling lingkaran
import math
r = float(input('masukkan jari-jari lingkaran: '))
luas = math.pi*math.pow(r,2)
keliling = math.pi*2*r
print([luas, keliling])

[50.26548245743669, 25.132741228718345]


In [11]:
# 3. menghittung sin cos tan
import math
sudut= float(input('masukkan besar sudut: '))
rad = math.radians(sudut)

sin = math.sin(rad)
cos = math.cos(rad)
tan = math.cos(rad)

degrees= math.degrees(sin)


print([sin, cos, tan, degrees])

[1.0, 6.123233995736766e-17, 6.123233995736766e-17, 57.29577951308232]


In [9]:
# 4. hitung logaritma
import math

basis = input('masukkan basis: ')
numerus = input('masukkan numerus: ')

try:
    basis = float(basis)
    numerus = float(numerus)
    if basis > 0 and basis != 1 and numerus > 0:
        print(math.log(numerus,basis))
    else:
        print('TyprError')
except ValueError:
    print('TypeError')

3.0


In [12]:
# menghitung faktorial

a = int(input('masukkan bilangan'))
faktorial = 1
fak = []
if a > 0:
    for i in range(1, a+1):
        faktorial = faktorial*i
        fak.append(i)
    print(faktorial)
    print(fak)
else:
    print('angka harus bilangan bulat lebih besar dari 0')

120
[1, 2, 3, 4, 5]


In [37]:
# mencari luas persegi dalam lingkaran
import math
r = int(input('masukkan jari2 lingkaran: '))
luaspersegi = 0.5*((2*r)**2)
luas = 2*r**2
luaslingkaran = math.pi*(r**2)
print(luaspersegi, luaslingkaran, luas)

32.0 50.26548245743669 32


### **DATA STRING**

In [57]:
a = 'Hello, World ' 
print(a[2:7])
for x in 'banana':
    print(x)
print(a[2:9])
print(a[2::-1])
print(a.lower())
print(a.upper())
print(a.strip())
print(a.replace('H', 'J'))


llo, 
b
a
n
a
n
a
llo, Wo
leH
hello, world 
HELLO, WORLD 
Hello, World


In [62]:
a = 'Hello, World'
print(a.swapcase())
print(a.index('e'))

hELLO, wORLD
1


In [53]:
import numpy as np

#### **SOAL PRAKTIKUM STRING**

In [27]:
a = 'Hello, World'
print(a.casefold())
print(a.lower())
print(a.center(23))
print(a.count('l'))
print(a.find('or'))
print(a.replace('H','W'))
b = a.split(' ')
print(b)

hello, world
hello, world
      Hello, World     
3
8
Wello, World
['Hello,', 'World']


In [28]:
# no 1. membalikkan string
a = input('masukkan kata: ')
print(a[::-1])

aybarus


In [13]:
#### **AOAL PRAKTIKUM STRING**

#### **SOAL RESPONSI STRING**

In [24]:
# membuat progrm lagu 'balonku ada lima' dengan mengganti jumlah balon dan warna balon meletus sesuai inputan
a = int(input('Masukkan banyak balon'))
b = input('masukkan warna balon yang meletus: ')
warna = ['merah', 'kuning', 'kelabu', 'merah muda', 'biru']

if a > 5:
    print('jumlah balon maksimal 5')
else:
    if b in warna[0:a]:
        print(f'balonku ada {a}, rupa-rupa warnanya,{warna[0:a]}, meletus balon {b} DORR, hatiku sangat kacau. balonku tinggal {a-1} kupegang erat-erat')
    else:
        print('pilih warna lain')




balonku ada 4, rupa-rupa warnanya,['merah', 'kuning', 'kelabu', 'merah muda'], meletus balon merah DORR, hatiku sangat kacau. balonku tinggal 3 kupegang erat-erat


In [21]:
#print terbalik
a =[1,2,3,4,5,6]
print(a[6:0:-1])
print(a[::-1])

[6, 5, 4, 3, 2]
[6, 5, 4, 3, 2, 1]


In [29]:
# membuat string jadi seperti ini
a = input('masukkan string')
for i in range(len(a)-1):
    print(a[i]+a[i+1])


qw
we
er
rt
ty


In [ ]:
paragraf =   """
Nama saya adalah Rita Sugiarto. Saya memiliki hobi menyanyi sejak kecil. Semua
berawal dari mimpi ibu saya untuk memiliki putri seorang penyanyi. Saya berlatih
vokal seminggu sekali dengan guru saya. Apabila saya menjadi juara satu dalam
perlombaan menyanyi tingkat provinsi, ibu saya akan membelikan saya kado yang
"""

if 'Mereka' in paragraf:
  print('Ada kata Mereka')
else:
  print('Tidak ada kata Mereka')

saya = paragraf.count("Saya")
saya_kecil = paragraf.count("saya")
Jumlahsaya = saya + saya_kecil
print('Jumlah kata Saya adalah', saya)
print('Jumlah kata saya adalah', saya_kecil)
print(f'Jumlah kata Saya dan saya adalah {Jumlahsaya}')

### **SOAL RESPONSI**

In [35]:
# membuaat lagu anak ayam
a = int(input('masukkan jumlah ayam'))

for i in range(a,0,-1):
    if i > 1:
        print(f'anak ayam turunlah {i} matilah satu tinggalah {i-1}')
    else:
        print('anak ayam tururnlah 1 matilah1 tinggal induknya')

anak ayam turunlah 4 matilah satu tinggalah 3
anak ayam turunlah 3 matilah satu tinggalah 2
anak ayam turunlah 2 matilah satu tinggalah 1
anak ayam tururnlah 1 matilah1 tinggal induknya


In [41]:
# kalkulator yang medahulukan pembagian dan perkalian
def kalkulator(num1,oper1,num2,oper2,num3):
    kali = 0
    bagi = 0
    x = 0
    if oper1 == '*':
        kali = kali + (num1*num2)
         if oper1 == '-':
            print((bagi + kali) - num1)
        elif oper1 == '+':
            print((bagi+kali) + num1)
    elif oper1== '/':
        bagi += (num1/num2)
        if oper1 == '-':
            print((bagi + kali) - num1)
        elif oper1 == '+':
            print((bagi+kali) + num1)

    elif oper2 == '*':
        kali += (num2*num3)
    elif oper2 == '/':
        bagi += (num2/num3)

    elif oper1 == '-':
        print((bagi + kali) - num1)
    elif oper1 == '+':
        print((bagi+kali) + num1)
    elif oper2 == '-':
        print((bagi + kali) - num3)
    elif oper2 == '+':
        print((bagi +kali) + num3)
    

kalkulator(2,'+',3,'*',2)

In [6]:
def kalkulator(angka, operasi):
    result = angka[0]

    for i in range(1, len(angka)):
        if operasi[i-1] == 1:  # Operasi +
            result += angka[i]
        elif operasi[i-1] == 2:  # Operasi *
            result *= angka[i]
        elif operasi[i-1] == 3:  # Operasi -
            result -= angka[i]
        elif operasi[i-1] == 4:  # Operasi /
            result /= angka[i]

    return result

# Contoh penggunaan
angka = [5, 6, 3]
operasi = [1, 4]  # 1 = +, 2 = *

hasil = kalkulator(angka, operasi)
print("Maka hasilnya adalah:", hasil)

Maka hasilnya adalah: 3.6666666666666665


In [42]:
def kalkulator(num1, oper1, num2, oper2, num3):
    hasil = 0
    
    if oper1 == '*':
        hasil = num1 * num2
    elif oper1 == '/':
        hasil = num1 / num2
    elif oper1 == '-':
        hasil = num1 - num2
    elif oper1 == '+':
        hasil = num1 + num2
    
    if oper2 == '*':
        hasil *= num3
    elif oper2 == '/':
        hasil /= num3
    elif oper2 == '-':
        hasil -= num3
    elif oper2 == '+':
        hasil += num3
    
    return hasil

hasil_kalkulator = kalkulator(2, '+', 3, '*', 2)
print(hasil_kalkulator)


10


In [2]:
def kalkulator(angka1, operasi1, angka2, operasi2, angka3):
    if operasi1 == '*' or operasi1 == '/':
        hasil1 = angka1 * angka2
    elif operasi1 == '+':
        hasil1 = angka1 + angka2
    elif operasi1 == '-':
        hasil1 = angka1 - angka2

    if operasi2 == '*' or operasi2 == '/':
        hasil2 = hasil1 * angka3
    elif operasi2 == '+':
        hasil2 = hasil1 + angka3
    elif operasi2 == '-':
        hasil2 = hasil1 - angka3

    return hasil2

angka1 = float(input("Masukkan angka pertama: "))
operasi1 = input("Masukkan operasi pertama (+, -, *, /): ")
angka2 = float(input("Masukkan angka kedua: "))
operasi2 = input("Masukkan operasi kedua (+, -, *, /): ")
angka3 = float(input("Masukkan angka ketiga: "))

hasil = kalkulator(angka1, operasi1, angka2, operasi2, angka3)
print("Hasil kalkulasi:", hasil)


Hasil kalkulasi: 10.0


### **DATA ARRAY**

In [9]:
#mencari nilai tertingi dalam dictionari dan nama key
mtk = { 'radam':10, 'evan': 90, 'aqila':80}
total = 0
nilai1 = ''
nilai_tertinggi=0
panjang = len(mtk.values())
for nama, nilai in mtk.items():
    total += nilai

    if nilai > nilai_tertinggi:
        nilai_tertinggi = nilai
        nilai1 = nama

print(total//panjang)
print(nilai1)


60
evan


In [17]:
mtk = { 'radam':10, 'evan': 90, 'aqila':80}
rata2 = sum(mtk.values())/ len(mtk)
a = max(mtk.values())
for nama, nilai in mtk.items():
    if nilai == a:
        nilai_tertinggi = nama
print(rata2)
print(nilai_tertinggi)

60.0
evan


In [15]:
mtk = { 'radam':10, 'evan': 90, 'aqila':80}
rata2 = sum(mtk.values())/ len(mtk)
tertinggi= max(mtk, key=mtk.get)

print(rata2)
print(tertinggi)


60.0
evan


##### **contoh penggunaan array pake numpy**

In [21]:
import numpy as np
total=int(input())
list=[]
for i in range(total):
    angka = int(input())
    list.append(angka)
x=np.array(list)
sorting=np.sort(x)

print('list asli: ',list)
print('array sorting: ', sorting)
print('array: ', x)

list asli:  [3, 4, 2, 6, 7]
array sorting:  [2 3 4 6 7]
[3 4 2 6 7]


##### **membuat array 1,2,3 dimensi**

In [25]:
a = np.array([1,2,3,4,5])
print(a)
print(a[1])
print(a[:2])

[1 2 3 4 5]
2
[1 2]


In [27]:
b=np.full((2,3),[[1,2,0],[3,4,5]])
print(b)
print(b[1,2])


[[1 2 0]
 [3 4 5]]
5


In [32]:
#mencari indeks angka di list
a =[12,5,30,52,8,27]
cari = int(input('masukkan angka yang dicari: '))
try:
    hasil = a.index(cari)
    print('ANGKA BERADA PADA INDEKS', hasil)
except ValueError:
    print('angka tidak ada')

angka tidak ada


In [24]:
# array kosong input
y = np.array([])
jumlah = int(input('masukkan jumlah: '))
for i in range(jumlah):
    x = int(input(f'masukkan angka ke {i+1}'))
    y = np.append(y,x)
print(y)
total = np.sum(y)
print(total)
print(total/len(y))

[1. 2. 3. 4. 5.]
15.0
3.0


In [23]:
import numpy as np
print(np.zeros(4))
print(np.ones(2))
print(np.empty(4))
print(np.full(4,5))
print(np.eye(4))
print(np.random.randint(2,10, size=(3,3)))

[0. 0. 0. 0.]
[1. 1.]
[0. 0. 0. 0.]
[5 5 5 5]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 2 4]
 [4 9 2]
 [9 6 5]]


In [30]:
a = np.array([1,2,3,4,5,5])
print(a[1:6:2])
print(a[::-2])
print(a[::-4])

[2 4 5]
[5 4 2]
[5 2]


In [39]:
import numpy as np
a = np.array([[1,2,3,4,7,4],[4,5,6,7,9,1]])
print(a)
print(a[0,2])
print(a[0,1:3])
print(a[1,2:6])

[[1 2 3 4 7 4]
 [4 5 6 7 9 1]]
3
[2 3]
[6 7 9 1]


In [ ]:
### Tugas Praktikum 
a = int(input('masukkan bilangan awal: '))
b = int(input('masukkan'))

#### **SOAL RESPONSI**

In [92]:
# mengembalikan indeks dari list bilangan prima
data = [2, 4, 7, 9, 11, 13, 15, 17, 19, 23, 25, 27, 29]
indeks = []
prim =[]

def prima(num):
    if num <= 1:
        return False
    for i in range(2, num):
        if num%i == 0:
            return False
    return True

for i in range(len(data)):
    if prima(data[i]):
        indeks.append(i)
print(indeks)

for x in data:
    if x > 1:
        for z in range(2, x):
            if x%z == 0:
                break
        else:
            prim.append(x)
print(prim)



[0, 2, 4, 5, 7, 8, 9, 12]
[2, 7, 11, 13, 17, 19, 23, 29]


In [ ]:
a = int(input('Masukkan panjang list: '))
list = []
if a >= 5:
  for i in range(a):
    b = int(input(f'Masukkan angka ke {i+1}: '))
    list.append(b)


In [38]:
# mengurutkan list ganjil genap
x = int(input('masukkan panjang list'))
lis= []
ganjil = []
genap = []
for i in range(x):
    angka = int(input(f'masukkan angka ke {i+1}'))
    lis.append(angka)
for z in lis:
    if z%2 == 0:
        genap.append(z)
    else:
        ganjil.append(z)
print(lis)
print(sorted(ganjil)+ sorted(genap))

[3, 4, 5, 2, 3, 77]
[3, 3, 5, 77, 2, 4]


In [44]:
a = input('masukkan list angkanya: ')
lissplit = a.split(',')
lissplit = [int(x) for x in lissplit]
genap = []
ganjil = []

for z in lissplit:
    if z%2 == 0:
        genap.append(z)
    else:
        ganjil.append(z)
print(lis)
print(sorted(ganjil)+ sorted(genap))

[3, 4, 5, 2, 3, 77]
[1, 3, 5, 2, 6, 8]


In [41]:
a = input('masukkan list angkanya: ')
lissplit = a.split(',')
genap = []
ganjil = []
print(lissplit)

['1', '2', '3', '4', '5', '6']


In [ ]:
a = input('kata: ')
y = []
for i in a:
  if i in 'AIUEOaiueo':
    y.append(i)
print(y)
print(len(y))

In [67]:
# menghitung umur

a = '04 - 07 - 2005'
b = '14 - 02 - 2024'
c = a.split()
d=b.split()
if int(c[2]) <= int(d[2]):
    if int(c[0]) <= int(d[0]):
        print('umur anda: ', int(d[4]) - int(d[4]), 'tahun')
else:
    print('umur anda: ', int(d[4])- int(c[4])-1, 'tahun')

umur anda:  18 tahun


In [74]:
a = [1,2,3,4,6,8]
b = int(input('masukkan angka yang dicari'))

if b in a:
    indeks = a.index(b)
    print(indeks)
else: 
    print('tidak')

print(indeks)

2
2


In [87]:
# mengurutkan bilangan prima
ax = [5,6,7,4,10,11,13]
a =[]

for i in ax:
    if i > 1:
        for x in range(2,i):
            if i%x == 0:
                break
        else:
            a.append(i) 
print(sorted(a))


[5, 7, 11, 13]


In [88]:
# mengganti prima dengan 0
ax = [5, 6, 7, 4, 10, 11, 13]

for i in range(len(ax)):
    if ax[i] > 1:
        for j in range(2, ax[i]):
            if ax[i] % j == 0:
                ax[i] = 0
                break

print(ax)


[5, 0, 7, 0, 0, 11, 13]
